### ISSUE TITLE
Adjust  display dimensions 

### ISSUE THREAD

**Issue by NAYANKOCHAR** [NavsiratS/SCM_TEAM-21#1]
make the improvement regarding the height and width of the Hangman game's display, aiming for better visibility and user experience.

**Comment by naveenchoudhary1234** [comment]
i have resolved the issue in [47f15a5](https://github.com/NavsiratS/SCM_TEAM-21/commit/47f15a5c6c56e3c9f63a92e307a02f362cbc5e48)
